logo: # add logo name
title: Thaddeus Hughes
description: > # this means to ignore newlines until "baseurl:"
  Passionate Engineer
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: #mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: I'M THAD. I MAKE THINGS. # add banner title
banner-desc: SIMULATION / MECHANICAL / ELECTRICAL / SOFTWARE / FABRICATION / TESTING # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Thaddeus Hughes
about-author: # about author
email: hughes.thad@gmail.com # your email
phone: (309)-530-0909 # your pnone number
website: http://thaddeus-maximus.github.io # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier:  # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 20
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

sass:
  sass_dir: _sass
