baseurl = "https://thadhughes.xyz/"
title = "Thaddeus Hughes."
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[markup.goldmark.renderer]
unsafe=true

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "thad"
  description = "Engineer, Etc."
  copyright = "&copy;2023 Thaddeus Hughes"
  sidebarAbout = [
    "Builder of <a href='/portfolio'>Technologies</a>, Maker of holy cards for <a href='https://www.littlecreators.shop'>Little Creators</a>, Host of <a href='https://www.machinaeexdeo.com'>Machinae Ex Deo</a>, President of <a href='https://www.manchestermakerspace.org'>Manchester Makerspace</a>.",
    "<b><a href='https://www.machinaeexdeo.com/subscribe/''>Subscribe</a> to my mailing list.</b>",
    ""
  ]

  #  "Basic Principles:",
  #  "1. Work (Avodah) is Worship.",
  #  "2. The material world is full of good things, although none of them are worth worshipping.",
  #  "3. Truth, Beauty and Goodness are one; worship of one at the expense of the others results in none.",
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "f/xknapzav"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  # home = true

  [[params.navlinks]]
  name = "Resume"
  url = "/Thad Hughes - Resume - 11APR2023.pdf"

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Splash"
  url = "splash/"
  home = true

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [[params.navlinks]]
  name = "Blog"
  url = "https://www.machinaeexdeo.com"

  [[params.navlinks]]
  name = "Podcast"
  url = "https://www.machinaeexdeo.com/podcast"


  [params.social]
  email         = "thad@thadhughes.xyz"
  youtube       = "https://www.youtube.com/channel/UC61GMHV-3Dq02XibxWoLkJg"
  instagram     = "https://instagram.com/machinaeexdeo/"
  github        = "https://github.com/Thaddeus-Maximus"
