baseURL = 'https://thadhughes.xyz/'
languageCode = 'en-us'
title = 'Hughes Engineering'
theme = 'graphpaper'

publishDir = 'docs'

[markup]
  [markup.asciidocExt]
    safeMode = 'unsafe'



[_build]
  publishResources = false


[params]
  default_header = "header.svg"
  default_header_href = "/"