baseURL = 'https://thadhughes.xyz/'
languageCode = 'en-us'
title = 'Thaddeus Hughes'
theme = 'scrapbook'

publishDir = 'docs'

[markup]
  [markup.asciidocExt]
    safeMode = 'unsafe'



[_build]
  publishResources = false


[params]
  default_header = "wordmark_wide.svg"
  default_header_href = "/"