baseURL = 'https://thadhughes.xyz/'
languageCode = 'en-us'
title = 'Thad Hughes Design'
theme = 'blackboard'

publishDir = 'docs'

[markup]
  [markup.asciidocExt]
    safeMode = 'unsafe'



[_build]
  publishResources = false


[params]
  default_header = "wordmark.svg"
  default_header_href = "/"